edited to allow user inputs
Issues: code working, but cannot push to git.
- was able to now see an error after updating the system a few times
- current error:
$ git push -u origin main

To https://github.com/megrad79/p0.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/megrad79/p0.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

- fix above issue at a later date; the error message is progress
- still having trouble downloading maven on a windows environment; reach out to collegues